# Where things are
# source:       "jekyll"
# destination:  ./blog

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
lsi:          false
excerpt_separator: "\n\n"

# Outputting
permalink:     /blog/:year-:month-:day/:title/
timezone:      null

#site config
title: Bumble Bee
subTitle: Starving for Knowledge.
url: http://omegaxy.com/
feed: /atom.xml
author: Omega

# Related Pages
page:
  - text: Main Page
    url: http://omegaxy.com
    last: true
  - text: Friend Links
    url: /blog/links.html
    last: true
  - text: About Me
    url: /blog/about.html
    last: false

# Nav Bar
nav:
  - text: Home
    url: /blog/index.html
    icon: icon-home
    class: home
  - text: Archive
    url: /blog/archives.html
    icon: icon-reorder
    class: none
  - text: About Me
    url: /blog/about.html
    icon: icon-envelope-alt
    class: none
  - text: Change Theme
    icon: icon-heart
    class: none
    rel: nofollow
    id: J-changeTheme
  - text: Search
    icon: icon-search
    class: none
    rel: nofollow
    id: search-btn
